spring:
  datasource:
    name: MySQL Connection
    url: jdbc:mysql://127.0.0.1:3306/e-lib?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: root
    password: Fx8P1200
    driver-class-name: com.mysql.cj.jdbc.Driver


# EMail configuration
email:
  host: smtp.gmail.com
    port: 578
    username: petar.vukcevic2001@gmail.com
    password: ""
