spring:
  application:
    name: E Lib
  profiles:
    active: dev

#    Cache configuration
  cache:
    jcache:
      config: classpath:cache/ehcache.xml


jwt:
  secret: c3VwZXJzZWNyZXRrZXk=
  validityInMinutes: 30 # access token
  refreshTokenValidityInMinutes: 60 # refresh token